
version: 2

models:
  - name: y4a_dwc_amz_cop_ovr

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - country
            - invoice_id

    columns:
      - name: country
        description: This is the country of invoice
        data_tests:
          - not_null

      - name: invoice_id
        data_tests:
          - not_null